ingress:
  hostname: cleandb.openenzymedb.platform.moleculemaker.org
  extraHosts:
  - cleandb.frontend.openenzymedb.mmli1.ncsa.illinois.edu
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "openenzymedb-oed-cors-header@kubernetescrd,openenzymedb-oed-redirect-to-login@kubernetescrd,openenzymedb-oed-private-auth@kubernetescrd,alphasynthesis-cleandb-prod-domain-redirect@kubernetescrd"

controller:
  image: moleculemaker/cleandb-frontend:main

config:
  hostname: "https://mmli.fastapi.mmli1.ncsa.illinois.edu"
  basePath: ""
  signInUrl: "https://auth.platform.moleculemaker.org/oauth2/start?rd=https%3A%2F%2Fcleandb.openenzymedb.platform.moleculemaker.org%2Fconfiguration"
  signOutUrl: "https://auth.platform.moleculemaker.org/oauth2/sign_out?rd=https%3A%2F%2Fcleandb.openenzymedb.platform.moleculemaker.org%2Fconfiguration"
  userInfoUrl: "https://auth.platform.moleculemaker.org/oauth2/userinfo"
  frontendOnly: "false"

extraDeploy:
- apiVersion: traefik.io/v1alpha1
  kind: Middleware
  metadata:
    name: cleandb-prod-domain-redirect
    namespace: alphasynthesis
  spec:
    redirectRegex:
      regex: "^https://cleandb.frontend.openenzymedb.mmli1.ncsa.illinois.edu/(.*)"
      replacement: "https://cleandb.openenzymedb.platform.moleculemaker.org/${1}"
      permanent: true
