/**
 * CLEAN Data API
 * API for accessing enzyme kinetic data from the CLEAN database  ## Automatic Pagination  When a query would return more than 5000 records and no explicit limit is provided, the API will automatically paginate results to return 5000 records at a time. The response will include pagination metadata with links to navigate to next and previous pages.  This threshold can be configured using the AUTO_PAGINATION_THRESHOLD environment variable. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Base model for CLEAN data.
 */
export interface CLEANDataBase { 
    /**
     * Unique identifier for the CLEAN predictions record.
     */
    predictions_uniprot_annot_id?: any | null;
    /**
     * Unique identifier for the Uniprot record.
     */
    uniprot?: any | null;
    /**
     * Status of the curation for the Uniprot record.
     */
    curation_status?: any | null;
    /**
     * Uniprot accession number.
     */
    accession?: any | null;
    /**
     * Name of the protein associated with the Uniprot record.
     */
    protein?: any | null;
    /**
     * Name of the organism associated with the Uniprot record.
     */
    organism?: any | null;
    /**
     * NCBI Taxonomy ID for the organism associated with the Uniprot record.
     */
    ncbi_tax_id?: any | null;
    /**
     * Length of the amino acid sequence associated with the Uniprot record.
     */
    amino_acids?: any | null;
    /**
     * Amino acid sequence of the protein associated with the Uniprot record.
     */
    sequence?: any | null;
    /**
     * Function of the enzyme associated with the Uniprot record.
     */
    _function?: any | null;
    /**
     * Name of the gene associated with the Uniprot record.
     */
    gene_name?: any | null;
    /**
     * List of CLEAN predicted EC numbers with associated confidence scores.
     */
    predicted_ec?: any | null;
    /**
     * List of annotated EC numbers associated with the Uniprot record. Each EC number is a string.
     */
    annot_ec_number_array?: any | null;
}

