/**
 * CLEAN Data API
 * API for accessing enzyme kinetic data from the CLEAN database  ## Automatic Pagination  When a query would return more than 5000 records and no explicit limit is provided, the API will automatically paginate results to return 5000 records at a time. The response will include pagination metadata with links to navigate to next and previous pages.  This threshold can be configured using the AUTO_PAGINATION_THRESHOLD environment variable. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model for the response of a CLEAN search query.
 */
export interface CLEANSearchResponse { 
    /**
     * Total number of records matching the query.
     */
    total?: any | null;
    /**
     * Maximum number of records returned.
     */
    limit?: any | null;
    /**
     * Number of records skipped.
     */
    offset?: any | null;
    /**
     * Whether results are automatically paginated.
     */
    auto_paginated?: any | null;
    /**
     * Link to the next page of results.
     */
    next?: any | null;
    /**
     * Link to the previous page of results.
     */
    previous?: any | null;
    /**
     * List of records matching the query.
     */
    data?: any | null;
}

