
version: '3.9'

networks:
  proxy:

services:
  cleandb:
    image: moleculemaker/cleandb-frontend:localdev
    container_name: cleandb-frontend
    build:
      context: .
    env_file:
      - .env
    ports:
      - 4200:80
    networks:
      - proxy

    restart: unless-stopped

    volumes:
     - ./src/assets/config/:/usr/share/nginx/html/assets/config
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
