# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: cleandb-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleandb-frontend
  template:
    metadata:
      labels:
        app: cleandb-frontend
    spec:
      containers:
        - name: cleandb-frontend
          image: {{ .Values.controller.image }}

          env:

          - name: JOB_MANAGER_API_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: hostname

          - name: JOB_MANAGER_API_BASEPATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: basePath

          - name: CLEANDB_API_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: cleandbHostname

          - name: CLEANDB_API_BASEPATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: cleandbBasePath

          - name: OAUTH_SIGNIN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: signInUrl

          - name: OAUTH_SIGNOUT_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: signOutUrl

          - name: OAUTH_USERINFO_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: userInfoUrl

          - name: FRONTEND_ONLY
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: frontendOnly

          ports:
            - containerPort: 80
          imagePullPolicy: Always
