name: Cron
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - cleandb.frontend.staging.mmli1.ncsa.illinois.edu
          - cleandb.platform.moleculemaker.org
    name: E2E on ${{ matrix.env }} (Cron)
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with private NPM packages
        run: |
          echo "@chemaxon:registry=https://hub.chemaxon.com/artifactory/api/npm/npm/" > $HOME/.npmrc
          echo "//hub.chemaxon.com/artifactory/api/npm/npm/:_auth=${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc
          echo "@moleculemaker:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN || secrets.GITHUB_TOKEN }}" >> $HOME/.npmrc
          echo "npmrc_path=$HOME/.npmrc" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          npm ci

      - name: Run E2E Tests
        run: |
          export TESTING_URL=${{ matrix.env }}
          xvfb-run --auto-servernum npx nightwatch ./nightwatch --env chrome
